apiVersion: rds.cluster/v1alpha1
kind: Rdsbackup
metadata:
  name: rdsbackup-once-example
spec:
  # Add fields here
  image: "harbor.gzky.com/dongxy-projects/rds:5.0.8"
  instance: "example"
  instance_storage:
    type: "nfs"
    class: "managed-nfs-storage"
  backup_storage:
    type: "minio"
    endpoint: "192.168.6.172:9000"
    bucket: "example"
    access_key: "minioadmin"
    secret_key: "minioadmin"
    ssl: false
  job_type: "once"

